<?php
/**
 * OptiMonk plugin for Magento
 *
 * @package     Wse_OptiMonk
 * @author      Tibor Berna
 */
?>
    <!-- OptiMonk Cart Data -->
<?php if ($this->isEnabled()) : ?>
    <?php $cartProducts = $this->getProducts(); ?>
    <script>
        document.querySelector('html').addEventListener('optimonk#ready', function () {
            var adapter = OptiMonk.Visitor.createAdapter();
            adapter.Cart.clear();
            <?php if(!empty($cartProducts)): ?>
                <?php foreach ($cartProducts as $sku => $productDetails) { ?>
                    adapter.Cart.add(<?php echo json_encode($sku); ?>, <?php echo json_encode($productDetails); ?>);
                <?php } ?>
            <?php endif; ?>
        });
    </script>
<?php endif; ?>